import airtag from "../assets/airtag.jpeg";
import iphone from "../assets/iphone.jpg";
import macbook from "../assets/macbook.jpeg";
import dongHo from "../assets/smartwatch.jpeg";
import ApplePencil from "../assets/pencil.jpeg";
import khan from "../assets/khan.jpeg";
import Airpods from "../assets/airpods.jpeg";
import chuot from "../assets/chuot.jpeg";
import trackpad from "../assets/trackpad.png";
import AppleVesion from "../assets/apple vesion.jpg";
import loa from "../assets/loaApple.jpg";
import AirpodsMax from "../assets/airport max.jpeg";
import SamSungTV from "../assets/samsungTV.jpg";
import MacMini from "../assets/macmini.jpg";
import MagSafe from "../assets/magsafe-apple.jpg";
import MagicKeyboard from "../assets/magic-keyboard.webp";
import AsusZenbook from "../assets/Laptop/asus-zenbook-14-oled.jpg";
import AsusVivoBook from "../assets/Laptop/asus viobook.jpg";
import AsusUltra from "../assets/Laptop/asus-ux5406sa-ultra-7.jpg";
import DellG15 from "../assets/Laptop/dell-g15-5530-i7.jpg";
import HpProBook from "../assets/Laptop/hp-probook.jpg";
import LenovoThinkbook from "../assets/Laptop/lenovo-thinkbook-14-ultra-7.jpg";
import MSIGaming from "../assets/Laptop/msi-gaming-sword-16.jpg";
import MSIKatana from "../assets/Laptop/msi-katana.jpg";
import SamSungGalaxy from "../assets/Laptop/samsung-galaxy-chromebook.jpg";
import AsusZenbook14 from "../assets/Laptop/asus-zenbook-14-oled.jpg";
import AccerSwiftLite from "../assets/Laptop/acer-swift-lite.jpg";
import HpEnvy from "../assets/Laptop/hp-envy-x360.jpg";

const LOCAL_STORAGE_KEY = "products";

// Function to get initial products from local storage or return default products
const getInitialProducts = () => {
  const storedProducts = localStorage.getItem(LOCAL_STORAGE_KEY);
  return storedProducts
    ? JSON.parse(storedProducts)
    : [
        {
          id: 1,
          name: "Air Tag",
          price: 36000000,
          image: airtag,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Keep dry, handle with care.",
          usageInstructions: "Refer to the user manual",
          dimensions: "32 x 32 x 8 mm",
          weight: "11 g",
          material: "Plastic",
          processor: {
            version: "Snapdragon 7 Gen 1",
            type: "Octa-Core",
            details: "1 x 2.4 GHz + 3 x 2.36 GHz + 4 x 1.8 GHz",
            cores: 8,
          },
          ram: "8 GB",
          display: {
            size: "1.4 inch",
            technology: "OLED",
            resolution: "320 x 320 pixels",
            colors: "16 Million",
            refreshRate: 60,
            brightness: "600 nits",
          },
          graphics: {
            gpu: "Adreno 644",
          },
          storage: {
            rom: "32 GB",
            expandable: false,
          },
          rearCamera: {
            count: 1,
            features: ["Time Lapse", "Night Mode"],
            video: "1080p@30fps",
            resolutions: ["8 MP"],
          },
          selfieCamera: {
            features: ["Beautify"],
            resolution: "5 MP",
          },
          security: ["Face unlock", "Pattern", "Password", "PIN"],
          specialFeatures: ["Double tap to wake"],
          communications: {
            simSlots: "No SIM",
            connector: "Bluetooth LE",
            wifi: "802.11 a/b/g/n",
            gps: "None",
            bluetooth: "v5.1",
            nfc: false,
          },
          battery: {
            type: "Lithium ion",
            capacity: "250 mAh",
          },
          os: {
            name: "iOS",
            version: "16",
          },
          boxContents: ["User Guide", "Warranty Card"],
        },
        {
          id: 2,
          name: "iPhone 16 Pro Max",
          price: 30000000,
          image: iphone,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a dry place, handle with care.",
          usageInstructions: "Refer to the user manual",
          dimensions: "163.9 x 76.5 x 7.8 mm",
          weight: "180 g",
          material: "Glass and Aluminum",
          processor: {
            version: "A17 Bionic",
            type: "Hexa-Core",
            details: "2 x high-performance cores + 4 x efficiency cores",
            cores: 6,
          },
          ram: "8 GB",
          display: {
            size: "6.7 inch",
            technology: "Super Retina XDR OLED",
            resolution: "1290 x 2796 Pixels",
            colors: "16 Million",
            refreshRate: 120,
            brightness: "2000 nits",
          },
          graphics: {
            gpu: "Apple-designed GPU",
          },
          storage: {
            rom: "256 GB",
            expandable: false,
          },
          rearCamera: {
            count: 3,
            features: ["Optical Zoom 10x", "Night Mode", "Panorama", "Macro"],
            video: "4K 2160p@60fps, 1080p@240fps",
            resolutions: ["50 MP", "12 MP", "10 MP"],
          },
          selfieCamera: {
            features: ["Beautify", "Portrait Mode"],
            resolution: "12 MP",
          },
          security: ["Face ID", "Pattern", "Password", "PIN"],
          specialFeatures: ["Double tap to wake", "Fast charging 45W"],
          communications: {
            simSlots: "2 Nano SIM, eSIM",
            connector: "Type C",
            wifi: "802.11 a/b/g/n/ac/ax",
            gps: "GPS, GLONASS, BEIDOU, GALILEO, QZSS",
            bluetooth: "v5.3",
            nfc: true,
          },
          battery: {
            type: "Lithium polymer",
            capacity: "5000 mAh",
          },
          os: {
            name: "iOS",
            version: "17",
          },
          boxContents: ["User Guide", "USB-C Cable", "SIM Eject Tool"],
        },
        {
          id: 3,
          name: "Laptop MacBook M4 Pro",
          price: 120000000,
          image: macbook,
          origin: "Vietnam",
          releaseDate: "01/2024",
          warranty: 24,
          storageInstructions: "Store in a cool, dry place",
          usageInstructions: "Refer to the user manual",
          dimensions: "304.1 x 212.4 x 15.6 mm",
          weight: "1.4 kg",
          material: "Aluminum",
          processor: {
            version: "Apple M4",
            type: "8-core CPU",
            details: "4 high-performance + 4 efficiency cores",
            cores: 8,
          },
          ram: "32 GB",
          display: {
            size: "16 inch",
            technology: "Liquid Retina XDR",
            resolution: "3456 x 2234 Pixels",
            colors: "16 Million",
            refreshRate: 120,
            brightness: "1600 nits",
          },
          graphics: {
            gpu: "Integrated 10-core GPU",
          },
          storage: {
            rom: "1 TB",
            expandable: false,
          },
          rearCamera: null,
          selfieCamera: {
            features: ["1080p FaceTime HD"],
            resolution: "1080p",
          },
          security: ["Touch ID"],
          specialFeatures: [
            "High-performance cooling",
            "Up to 20 hours battery life",
          ],
          communications: {
            simSlots: "No SIM",
            connector: "Thunderbolt 4 / USB 4",
            wifi: "802.11ax Wi-Fi 6E",
            gps: "None",
            bluetooth: "v5.2",
            nfc: false,
          },
          battery: {
            type: "Lithium polymer",
            capacity: "100 watt-hour",
          },
          os: {
            name: "macOS",
            version: "Ventura",
          },
          boxContents: ["User Guide", "USB-C Charger", "Charging Cable"],
        },
        {
          id: 4,
          name: "Apple Watch Series 8",
          price: 12000000,
          image: dongHo,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "45 x 38 x 10.7 mm",
          weight: "32 g",
          material: "Aluminum and Ceramic",
          processor: {
            version: "Apple S8",
            type: "Dual-Core",
            details: "64-bit architecture",
            cores: 2,
          },
          ram: "1 GB",
          display: {
            size: "1.9 inch",
            technology: "LTPO OLED",
            resolution: "396 x 484 pixels",
            colors: "16 Million",
            refreshRate: 60,
            brightness: "1000 nits",
          },
          graphics: {
            gpu: "Integrated GPU",
          },
          storage: {
            rom: "32 GB",
            expandable: false,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["PIN", "Face unlock"],
          specialFeatures: ["Heart Rate Monitor", "Blood Oxygen Sensor", "ECG"],
          communications: {
            simSlots: "eSIM",
            connector: "Bluetooth LE",
            wifi: "802.11 b/g/n",
            gps: "GPS, GLONASS, BEIDOU",
            bluetooth: "v5.3",
            nfc: true,
          },
          battery: {
            type: "Lithium polymer",
            capacity: "308 mAh",
          },
          os: {
            name: "watchOS",
            version: "9",
          },
          boxContents: ["User Guide", "Magnetic Charger"],
        },
        {
          id: 5,
          name: "Apple Pencil (2nd Gen)",
          price: 3500000,
          image: ApplePencil,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Keep in a safe, dry place to avoid damage.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "166 x 8.9 mm",
          weight: "20.7 g",
          material: "Plastic",
          processor: {
            version: "Custom Apple Chip",
            type: "Single-Core",
            details: "Optimized for input processing",
            cores: 1,
          },
          ram: "512 MB",
          display: null,
          graphics: null,
          storage: {
            rom: "4 GB",
            expandable: false,
          },
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: [
            "Double tap to switch tools",
            "Magnetic attach and charge",
          ],
          communications: {
            simSlots: null,
            connector: "Magnetic charging",
            wifi: null,
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium ion",
            capacity: "10 mAh",
          },
          os: {
            name: null,
            version: null,
          },
          boxContents: ["User Guide"],
        },
        {
          id: 6,
          name: "Apple Cloth",
          price: 500000,
          image: khan,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a dry place.",
          usageInstructions: "Use gently on screens.",
          dimensions: "180 x 180 mm",
          weight: "5 g",
          material: "Microfiber",
          processor: null,
          ram: null,
          display: null,
          graphics: null,
          storage: null,
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: ["Scratch-resistant fabric"],
          communications: {
            simSlots: null,
            connector: null,
            wifi: null,
            gps: null,
            bluetooth: null,
            nfc: null,
          },
          battery: null,
          os: null,
          boxContents: ["User Guide"],
        },
        {
          id: 7,
          name: "AirPods Pro",
          price: 5500000,
          image: Airpods,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Keep in the case when not in use.",
          usageInstructions: "Refer to the user manual.",
          dimensions:
            "Earbud: 30.9 x 21.8 x 24 mm; Case: 45.2 x 60.6 x 21.7 mm",
          weight: "Earbud: 5.4 g each; Case: 45.6 g",
          material: "Plastic",
          processor: {
            version: "Apple H2",
            type: "Audio Processor",
            details: "Optimized for noise cancellation and spatial audio",
            cores: 2,
          },
          ram: "512 MB",
          display: null,
          graphics: null,
          storage: {
            rom: "16 GB",
            expandable: false,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Ear detection"],
          specialFeatures: ["Active Noise Cancellation", "Transparency Mode"],
          communications: {
            simSlots: null,
            connector: "Lightning",
            wifi: null,
            gps: null,
            bluetooth: "v5.3",
            nfc: false,
          },
          battery: {
            type: "Lithium ion",
            capacity: "Battery life up to 24 hours with case",
          },
          os: {
            name: null,
            version: null,
          },
          boxContents: ["User Guide", "Charging Cable", "Silicone Ear Tips"],
        },
        {
          id: 8,
          name: "Magic Mouse",
          price: 2500000,
          image: chuot,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a safe place to avoid scratches.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "113.5 x 58.1 x 21.3 mm",
          weight: "99 g",
          material: "Plastic",
          processor: null,
          ram: null,
          display: null,
          graphics: null,
          storage: null,
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: ["Multi-touch gestures"],
          communications: {
            simSlots: null,
            connector: "Lightning",
            wifi: null,
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Rechargeable",
            capacity: "Lasts up to 1 month per charge",
          },
          os: null,
          boxContents: ["User Guide", "Lightning to USB Cable"],
        },
        {
          id: 9,
          name: "Magic Trackpad",
          price: 3500000,
          image: trackpad,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a safe place to avoid scratches.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "160 x 114.9 x 10.9 mm",
          weight: "231 g",
          material: "Aluminum and Glass",
          processor: null,
          ram: null,
          display: null,
          graphics: null,
          storage: null,
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: ["Force Touch, Multi-touch gestures"],
          communications: {
            simSlots: null,
            connector: "USB-C",
            wifi: null,
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Rechargeable",
            capacity: "Lasts up to 1 month per charge",
          },
          os: null,
          boxContents: ["User Guide", "USB-C to USB-C Cable"],
        },
        {
          id: 10,
          name: "Apple Vision",
          price: 70000000,
          image: AppleVesion,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "Unknown",
          weight: "500 g",
          material: "Glass and Aluminum",
          processor: {
            version: "Apple R1",
            type: "10-core CPU",
            details: "Optimized for AR/VR applications",
            cores: 10,
          },
          ram: "16 GB",
          display: {
            size: "Dual 4K",
            technology: "Micro-OLED",
            resolution: "4096 x 4096 per eye",
            colors: "1 Billion",
            refreshRate: 90,
            brightness: "1000 nits",
          },
          graphics: {
            gpu: "Integrated 12-core GPU",
          },
          storage: {
            rom: "1 TB",
            expandable: false,
          },
          rearCamera: null,
          selfieCamera: {
            features: ["Wide-angle", "Depth sensing"],
          },
          security: ["Eye tracking", "Face recognition"],
          specialFeatures: ["Mixed Reality, Eye Tracking, Hand Gestures"],
          communications: {
            simSlots: null,
            connector: "USB-C",
            wifi: "Wi-Fi 6E",
            gps: "Indoor positioning",
            bluetooth: "v5.3",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "Lasts up to 2 hours on a single charge",
          },
          os: {
            name: "visionOS",
            version: "1.0",
          },
          boxContents: ["User Guide", "Charging Cable"],
        },
        {
          id: 11,
          name: "AirPods Max",
          price: 12000000,
          image: AirpodsMax,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a safe place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "Unknown",
          weight: "385 g",
          material: "Aluminum and Plastic",
          processor: {
            version: "Apple H1",
            type: "Audio Processor",
            details: "Optimized for high-fidelity audio",
            cores: 1,
          },
          ram: "1 GB",
          display: null,
          graphics: null,
          storage: {
            rom: "32 GB",
            expandable: false,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Ear detection"],
          specialFeatures: ["Active Noise Cancellation", "Transparency Mode"],
          communications: {
            simSlots: null,
            connector: "Lightning",
            wifi: null,
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "Lasts up to 20 hours with ANC on",
          },
          os: {
            name: null,
            version: null,
          },
          boxContents: ["User Guide", "Charging Cable", "Carrying Case"],
        },
        {
          id: 12,
          name: "Loa Aplle",
          price: 7000000,
          image: loa,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "Unknown",
          weight: "1 kg",
          material: "Plastic",
          processor: null,
          ram: null,
          display: null,
          graphics: null,
          storage: null,
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: ["High-quality sound", "Bluetooth connectivity"],
          communications: {
            simSlots: null,
            connector: "Bluetooth",
            wifi: null,
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "Lasts up to 10 hours",
          },
          os: null,
          boxContents: ["User Guide", "Charging Cable"],
        },
        {
          id: 13,
          name: "Loa Aplle",
          price: 7000000,
          image: loa,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "Unknown",
          weight: "1 kg",
          material: "Plastic",
          processor: null,
          ram: null,
          display: null,
          graphics: null,
          storage: null,
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: ["High-quality sound", "Bluetooth connectivity"],
          communications: {
            simSlots: null,
            connector: "Bluetooth",
            wifi: null,
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "Lasts up to 10 hours",
          },
          os: null,
          boxContents: ["User Guide", "Charging Cable"],
        },
        {
          id: 14,
          name: "Loa Aplle",
          price: 7000000,
          image: loa,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "Unknown",
          weight: "1 kg",
          material: "Plastic",
          processor: null,
          ram: null,
          display: null,
          graphics: null,
          storage: null,
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: ["High-quality sound", "Bluetooth connectivity"],
          communications: {
            simSlots: null,
            connector: "Bluetooth",
            wifi: null,
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "Lasts up to 10 hours",
          },
          os: null,
          boxContents: ["User Guide", "Charging Cable"],
        },
        {
          id: 15,
          name: "Loa Aplle",
          price: 7000000,
          image: loa,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "Unknown",
          weight: "1 kg",
          material: "Plastic",
          processor: null,
          ram: null,
          display: null,
          graphics: null,
          storage: null,
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: ["High-quality sound", "Bluetooth connectivity"],
          communications: {
            simSlots: null,
            connector: "Bluetooth",
            wifi: null,
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "Lasts up to 10 hours",
          },
          os: null,
          boxContents: ["User Guide", "Charging Cable"],
        },
        {
          id: 16,
          name: "SamSung TV 4K",
          price: 5000000,
          image: SamSungTV,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Connect to TV via HDMI.",
          dimensions: "98 x 98 x 35 mm",
          weight: "425 g",
          material: "Plastic and aluminum",
          processor: {
            version: "A12 Bionic",
            type: "Hexa-core",
            details: "Optimized for high-performance streaming and gaming",
            cores: 6,
          },
          ram: "3 GB",
          display: null,
          graphics: {
            gpu: "Integrated GPU",
          },
          storage: {
            rom: "32 GB or 64 GB",
            expandable: false,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["PIN and Face Recognition"],
          specialFeatures: ["Dolby Vision", "HDR10+", "Siri Remote"],
          communications: {
            simSlots: null,
            connector: "HDMI, Ethernet",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion (Siri Remote)",
            capacity: "Remote lasts several months per charge",
          },
          os: {
            name: "tvOS",
            version: "14",
          },
          boxContents: ["User Guide", "Siri Remote", "Power Cord"],
        },
        {
          id: 17,
          name: "Apple Mac Mini",
          price: 20000000,
          image: MacMini,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a well-ventilated space.",
          usageInstructions: "Connect to display and keyboard.",
          dimensions: "197 x 197 x 36 mm",
          weight: "1.2 kg",
          material: "Aluminum",
          processor: {
            version: "M2",
            type: "8-core CPU",
            details: "4 performance cores and 4 efficiency cores",
            cores: 8,
          },
          ram: "8 GB (configurable up to 64 GB)",
          display: null,
          graphics: {
            gpu: "10-core integrated GPU",
          },
          storage: {
            rom: "256 GB (configurable up to 2 TB)",
            expandable: false,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Secure Enclave"],
          specialFeatures: ["Ultra-fast SSD", "High-efficiency cooling"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI, Ethernet",
            wifi: "Wi-Fi 6E",
            gps: null,
            bluetooth: "v5.3",
            nfc: false,
          },
          battery: null,
          os: {
            name: "macOS",
            version: "Ventura",
          },
          boxContents: ["User Guide", "Power Cord"],
        },
        {
          id: 18,
          name: "Apple MagSafe Charger",
          price: 1500000,
          image: MagSafe,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a dry place.",
          usageInstructions:
            "Attach to iPhone or AirPods for wireless charging.",
          dimensions: "60 x 60 x 8 mm",
          weight: "30 g",
          material: "Aluminum and Plastic",
          processor: null,
          ram: null,
          display: null,
          graphics: null,
          storage: null,
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: ["Fast wireless charging up to 15W"],
          communications: {
            simSlots: null,
            connector: "USB-C",
            wifi: null,
            gps: null,
            bluetooth: null,
            nfc: null,
          },
          battery: null,
          os: null,
          boxContents: ["User Guide"],
        },
        {
          id: 19,
          name: "Apple Magic Keyboard",
          price: 3000000,
          image: MagicKeyboard,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Connect to Mac via Bluetooth or USB.",
          dimensions: "279 x 114 x 11 mm",
          weight: "239 g",
          material: "Aluminum",
          processor: null,
          ram: null,
          display: null,
          graphics: null,
          storage: null,
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: [
            "Rechargeable battery",
            "Optimized scissor mechanism",
          ],
          communications: {
            simSlots: null,
            connector: "Lightning to USB-C",
            wifi: null,
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Rechargeable lithium-ion",
            capacity: "Lasts up to 1 month per charge",
          },
          os: null,
          boxContents: ["User Guide", "Lightning to USB-C Cable"],
        },
        {
          id: 20,
          name: "Apple Magic Keyboard",
          price: 3000000,
          image: MagicKeyboard,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Connect to Mac via Bluetooth or USB.",
          dimensions: "279 x 114 x 11 mm",
          weight: "239 g",
          material: "Aluminum",
          processor: null,
          ram: null,
          display: null,
          graphics: null,
          storage: null,
          rearCamera: null,
          selfieCamera: null,
          security: [],
          specialFeatures: [
            "Rechargeable battery",
            "Optimized scissor mechanism",
          ],
          communications: {
            simSlots: null,
            connector: "Lightning to USB-C",
            wifi: null,
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Rechargeable lithium-ion",
            capacity: "Lasts up to 1 month per charge",
          },
          os: null,
          boxContents: ["User Guide", "Lightning to USB-C Cable"],
        },
        {
          id: 21,
          name: "Laptop Asus Zenbook 14 OLED",
          price: 25000000,
          image: AsusZenbook,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "319 x 210 x 14 mm",
          weight: "1.3 kg",
          material: "Aluminum",
          processor: {
            version: "Intel i7",
            type: "Quad-Core",
            details: "4 x 2.8 GHz",
            cores: 4,
          },
          ram: "16 GB",
          display: {
            size: "14 inch",
            technology: "OLED",
            resolution: "2880 x 1800 pixels",
            colors: "16 Million",
            refreshRate: 90,
            brightness: "400 nits",
          },
          graphics: {
            gpu: "Intel Iris Xe",
          },
          storage: {
            rom: "512 GB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard", "Fast Charging"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "67 Wh",
          },
          os: {
            name: "Windows",
            version: "11",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 22,
          name: "Laptop Asus VivoBook",
          price: 20000000,
          image: AsusVivoBook,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "324 x 215 x 19 mm",
          weight: "1.8 kg",
          material: "Plastic",
          processor: {
            version: "Intel i5",
            type: "Quad-Core",
            details: "4 x 2.4 GHz",
            cores: 4,
          },
          ram: "8 GB",
          display: {
            size: "15.6 inch",
            technology: "IPS",
            resolution: "1920 x 1080 pixels",
            colors: "16 Million",
            refreshRate: 60,
            brightness: "250 nits",
          },
          graphics: {
            gpu: "NVIDIA GeForce MX250",
          },
          storage: {
            rom: "256 GB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 5",
            gps: null,
            bluetooth: "v4.2",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "42 Wh",
          },
          os: {
            name: "Windows",
            version: "10",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 23,
          name: "Laptop Asus Ultra",
          price: 30000000,
          image: AsusUltra,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "356 x 230 x 18 mm",
          weight: "2 kg",
          material: "Aluminum",
          processor: {
            version: "Intel i9",
            type: "Octa-Core",
            details: "8 x 3.0 GHz",
            cores: 8,
          },
          ram: "32 GB",
          display: {
            size: "17 inch",
            technology: "IPS",
            resolution: "3840 x 2160 pixels",
            colors: "16 Million",
            refreshRate: 120,
            brightness: "500 nits",
          },
          graphics: {
            gpu: "NVIDIA GeForce RTX 3060",
          },
          storage: {
            rom: "1 TB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard", "Fast Charging"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.1",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "90 Wh",
          },
          os: {
            name: "Windows",
            version: "11",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 24,
          name: "Laptop Dell G15",
          price: 28000000,
          image: DellG15,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "357 x 272 x 25 mm",
          weight: "2.5 kg",
          material: "Plastic",
          processor: {
            version: "AMD Ryzen 7",
            type: "Octa-Core",
            details: "8 x 3.2 GHz",
            cores: 8,
          },
          ram: "16 GB",
          display: {
            size: "15.6 inch",
            technology: "IPS",
            resolution: "1920 x 1080 pixels",
            colors: "16 Million",
            refreshRate: 144,
            brightness: "300 nits",
          },
          graphics: {
            gpu: "NVIDIA GeForce GTX 1660 Ti",
          },
          storage: {
            rom: "512 GB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard", "Fast Charging"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "86 Wh",
          },
          os: {
            name: "Windows",
            version: "11",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 25,
          name: "Laptop HP ProBook",
          price: 18000000,
          image: HpProBook,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "360 x 256 x 23 mm",
          weight: "2.1 kg",
          material: "Plastic and Aluminum",
          processor: {
            version: "Intel i5",
            type: "Quad-Core",
            details: "4 x 2.5 GHz",
            cores: 4,
          },
          ram: "8 GB",
          display: {
            size: "15.6 inch",
            technology: "LED",
            resolution: "1920 x 1080 pixels",
            colors: "16 Million",
            refreshRate: 60,
            brightness: "250 nits",
          },
          graphics: {
            gpu: "Intel UHD Graphics",
          },
          storage: {
            rom: "256 GB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard", "Fast Charging"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "4500 mAh",
          },
          os: {
            name: "Windows",
            version: "11",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 26,
          name: "Laptop Lenovo Thinkbook",
          price: 22000000,
          image: LenovoThinkbook,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "323 x 218 x 17 mm",
          weight: "1.5 kg",
          material: "Aluminum",
          processor: {
            version: "Intel i7",
            type: "Quad-Core",
            details: "4 x 2.8 GHz",
            cores: 4,
          },
          ram: "16 GB",
          display: {
            size: "14 inch",
            technology: "IPS",
            resolution: "1920 x 1080 pixels",
            colors: "16 Million",
            refreshRate: 60,
            brightness: "300 nits",
          },
          graphics: {
            gpu: "Intel Iris Xe",
          },
          storage: {
            rom: "512 GB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard", "Fast Charging"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "60 Wh",
          },
          os: {
            name: "Windows",
            version: "11",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 27,
          name: "Laptop MSI Gaming Sword 16",
          price: 32000000,
          image: MSIGaming,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "359 x 259 x 24 mm",
          weight: "2.3 kg",
          material: "Plastic",
          processor: {
            version: "Intel i7",
            type: "Hexa-Core",
            details: "6 x 2.6 GHz",
            cores: 6,
          },
          ram: "16 GB",
          display: {
            size: "16 inch",
            technology: "IPS",
            resolution: "2560 x 1440 pixels",
            colors: "16 Million",
            refreshRate: 165,
            brightness: "350 nits",
          },
          graphics: {
            gpu: "NVIDIA GeForce RTX 3070",
          },
          storage: {
            rom: "1 TB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard", "Fast Charging"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.1",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "99 Wh",
          },
          os: {
            name: "Windows",
            version: "11",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 28,
          name: "Laptop MSI Katana",
          price: 27000000,
          image: MSIKatana,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "359 x 259 x 24 mm",
          weight: "2.3 kg",
          material: "Plastic",
          processor: {
            version: "Intel i5",
            type: "Quad-Core",
            details: "4 x 2.4 GHz",
            cores: 4,
          },
          ram: "8 GB",
          display: {
            size: "15.6 inch",
            technology: "IPS",
            resolution: "1920 x 1080 pixels",
            colors: "16 Million",
            refreshRate: 144,
            brightness: "250 nits",
          },
          graphics: {
            gpu: "NVIDIA GeForce GTX 1650",
          },
          storage: {
            rom: "512 GB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard", "Fast Charging"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "53 Wh",
          },
          os: {
            name: "Windows",
            version: "11",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 29,
          name: "Laptop Samsung Galaxy Chromebook",
          price: 23000000,
          image: SamSungGalaxy,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "302 x 203 x 9.9 mm",
          weight: "1.0 kg",
          material: "Aluminum",
          processor: {
            version: "Intel i5",
            type: "Quad-Core",
            details: "4 x 2.4 GHz",
            cores: 4,
          },
          ram: "8 GB",
          display: {
            size: "13.3 inch",
            technology: "AMOLED",
            resolution: "3840 x 2160 pixels",
            colors: "16 Million",
            refreshRate: 60,
            brightness: "400 nits",
          },
          graphics: {
            gpu: "Intel UHD Graphics",
          },
          storage: {
            rom: "256 GB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard", "Fast Charging"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "49.2 Wh",
          },
          os: {
            name: "Chrome OS",
            version: "Latest",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 30,
          name: "Asus Zenbook 14 OLED",
          price: 25000000,
          image: AsusZenbook14,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "319 x 210 x 14 mm",
          weight: "1.3 kg",
          material: "Aluminum",
          processor: {
            version: "Intel i7",
            type: "Quad-Core",
            details: "4 x 2.8 GHz",
            cores: 4,
          },
          ram: "16 GB",
          display: {
            size: "14 inch",
            technology: "OLED",
            resolution: "2880 x 1800 pixels",
            colors: "16 Million",
            refreshRate: 90,
            brightness: "400 nits",
          },
          graphics: {
            gpu: "Intel Iris Xe",
          },
          storage: {
            rom: "512 GB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard", "Fast Charging"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "67 Wh",
          },
          os: {
            name: "Windows",
            version: "11",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 31,
          name: "Acer Swift Lite",
          price: 22000000,
          image: AccerSwiftLite,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "320 x 215 x 15 mm",
          weight: "1.2 kg",
          material: "Aluminum",
          processor: {
            version: "Intel i5",
            type: "Quad-Core",
            details: "4 x 2.4 GHz",
            cores: 4,
          },
          ram: "8 GB",
          display: {
            size: "14 inch",
            technology: "IPS",
            resolution: "1920 x 1080 pixels",
            colors: "16 Million",
            refreshRate: 60,
            brightness: "300 nits",
          },
          graphics: {
            gpu: "Intel UHD Graphics",
          },
          storage: {
            rom: "256 GB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 5",
            gps: null,
            bluetooth: "v4.2",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "50 Wh",
          },
          os: {
            name: "Windows",
            version: "10",
          },
          boxContents: ["User Guide", "Charger"],
        },
        {
          id: 32,
          name: "HP Envy x360",
          price: 28000000,
          image: HpEnvy,
          origin: "Vietnam",
          releaseDate: "07/2024",
          warranty: 12,
          storageInstructions: "Store in a cool, dry place.",
          usageInstructions: "Refer to the user manual.",
          dimensions: "358 x 230 x 18 mm",
          weight: "1.8 kg",
          material: "Aluminum",
          processor: {
            version: "AMD Ryzen 7",
            type: "Octa-Core",
            details: "8 x 2.9 GHz",
            cores: 8,
          },
          ram: "16 GB",
          display: {
            size: "15.6 inch",
            technology: "IPS",
            resolution: "1920 x 1080 pixels",
            colors: "16 Million",
            refreshRate: 60,
            brightness: "300 nits",
          },
          graphics: {
            gpu: "AMD Radeon Graphics",
          },
          storage: {
            rom: "512 GB SSD",
            expandable: true,
          },
          rearCamera: null,
          selfieCamera: null,
          security: ["Fingerprint"],
          specialFeatures: ["Backlit Keyboard", "360-degree hinge"],
          communications: {
            simSlots: null,
            connector: "USB-C, HDMI",
            wifi: "Wi-Fi 6",
            gps: null,
            bluetooth: "v5.0",
            nfc: false,
          },
          battery: {
            type: "Lithium-ion",
            capacity: "51 Wh",
          },
          os: {
            name: "Windows",
            version: "11",
          },
          boxContents: ["User Guide", "Charger"],
        },
      ];
};

let products = getInitialProducts();

export const getProducts = () => {
  return products;
};

export const addProduct = (newProduct) => {
  products.push(newProduct);
  localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(products));
};
